// Mocks generated by Mockito 5.4.6 from annotations
// in zarza_ai/test/presentation/queue/offline_queue_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:zarza_ai/core/services/sync_service.dart' as _i6;
import 'package:zarza_ai/domain/entities/pending_upload.dart' as _i4;
import 'package:zarza_ai/domain/usecases/delete_pending_upload_usecase.dart'
    as _i5;
import 'package:zarza_ai/domain/usecases/watch_pending_uploads_usecase.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [WatchPendingUploadsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockWatchPendingUploadsUseCase extends _i1.Mock
    implements _i2.WatchPendingUploadsUseCase {
  MockWatchPendingUploadsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<List<_i4.PendingUpload>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i3.Stream<List<_i4.PendingUpload>>.empty(),
          )
          as _i3.Stream<List<_i4.PendingUpload>>);
}

/// A class which mocks [DeletePendingUploadUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeletePendingUploadUseCase extends _i1.Mock
    implements _i5.DeletePendingUploadUseCase {
  MockDeletePendingUploadUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> call(String? offlineSyncId) =>
      (super.noSuchMethod(
            Invocation.method(#call, [offlineSyncId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [SyncService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSyncService extends _i1.Mock implements _i6.SyncService {
  MockSyncService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> syncPending() =>
      (super.noSuchMethod(
            Invocation.method(#syncPending, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
