// Mocks generated by Mockito 5.4.6 from annotations
// in zarza_ai/test/data/repositories/offline_queue_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:zarza_ai/data/datasources/local_queue_datasource.dart' as _i2;
import 'package:zarza_ai/domain/entities/pending_upload.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [LocalQueueDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalQueueDatasource extends _i1.Mock
    implements _i2.LocalQueueDatasource {
  MockLocalQueueDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> enqueue(_i4.PendingUpload? item) =>
      (super.noSuchMethod(
            Invocation.method(#enqueue, [item]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.PendingUpload>> getPending() =>
      (super.noSuchMethod(
            Invocation.method(#getPending, []),
            returnValue: _i3.Future<List<_i4.PendingUpload>>.value(
              <_i4.PendingUpload>[],
            ),
          )
          as _i3.Future<List<_i4.PendingUpload>>);

  @override
  _i3.Future<void> updateItem(_i4.PendingUpload? item) =>
      (super.noSuchMethod(
            Invocation.method(#updateItem, [item]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> delete(String? offlineSyncId) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [offlineSyncId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Stream<List<_i4.PendingUpload>> watchAll() =>
      (super.noSuchMethod(
            Invocation.method(#watchAll, []),
            returnValue: _i3.Stream<List<_i4.PendingUpload>>.empty(),
          )
          as _i3.Stream<List<_i4.PendingUpload>>);

  @override
  _i3.Future<int> countPending() =>
      (super.noSuchMethod(
            Invocation.method(#countPending, []),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<void> resetSyncing() =>
      (super.noSuchMethod(
            Invocation.method(#resetSyncing, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
