// Mocks generated by Mockito 5.4.6 from annotations
// in zarza_ai/test/data/repositories/offline_aware_ingestion_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:io' as _i8;

import 'package:mockito/mockito.dart' as _i1;
import 'package:zarza_ai/core/services/connectivity_service.dart' as _i3;
import 'package:zarza_ai/core/services/local_notifications_service.dart'
    as _i10;
import 'package:zarza_ai/data/datasources/remote_ingestion_datasource.dart'
    as _i7;
import 'package:zarza_ai/data/models/upload_response_model.dart' as _i2;
import 'package:zarza_ai/domain/entities/pending_upload.dart' as _i6;
import 'package:zarza_ai/domain/entities/upload_metadata.dart' as _i9;
import 'package:zarza_ai/domain/repositories/i_offline_queue_repository.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeUploadResponseModel_0 extends _i1.SmartFake
    implements _i2.UploadResponseModel {
  _FakeUploadResponseModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ConnectivityService].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectivityService extends _i1.Mock
    implements _i3.ConnectivityService {
  MockConnectivityService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> isConnected() =>
      (super.noSuchMethod(
            Invocation.method(#isConnected, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);
}

/// A class which mocks [IOfflineQueueRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIOfflineQueueRepository extends _i1.Mock
    implements _i5.IOfflineQueueRepository {
  MockIOfflineQueueRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> enqueue(_i6.PendingUpload? item) =>
      (super.noSuchMethod(
            Invocation.method(#enqueue, [item]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i6.PendingUpload>> getPending() =>
      (super.noSuchMethod(
            Invocation.method(#getPending, []),
            returnValue: _i4.Future<List<_i6.PendingUpload>>.value(
              <_i6.PendingUpload>[],
            ),
          )
          as _i4.Future<List<_i6.PendingUpload>>);

  @override
  _i4.Future<void> updateItem(_i6.PendingUpload? item) =>
      (super.noSuchMethod(
            Invocation.method(#updateItem, [item]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> delete(String? offlineSyncId) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [offlineSyncId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Stream<List<_i6.PendingUpload>> watchAll() =>
      (super.noSuchMethod(
            Invocation.method(#watchAll, []),
            returnValue: _i4.Stream<List<_i6.PendingUpload>>.empty(),
          )
          as _i4.Stream<List<_i6.PendingUpload>>);

  @override
  _i4.Future<int> countPending() =>
      (super.noSuchMethod(
            Invocation.method(#countPending, []),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<void> resetSyncing() =>
      (super.noSuchMethod(
            Invocation.method(#resetSyncing, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [RemoteIngestionDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoteIngestionDatasource extends _i1.Mock
    implements _i7.RemoteIngestionDatasource {
  MockRemoteIngestionDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.UploadResponseModel> uploadImage(
    _i8.File? image,
    _i9.UploadMetadata? metadata,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#uploadImage, [image, metadata]),
            returnValue: _i4.Future<_i2.UploadResponseModel>.value(
              _FakeUploadResponseModel_0(
                this,
                Invocation.method(#uploadImage, [image, metadata]),
              ),
            ),
          )
          as _i4.Future<_i2.UploadResponseModel>);
}

/// A class which mocks [LocalNotificationsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalNotificationsService extends _i1.Mock
    implements _i10.LocalNotificationsService {
  MockLocalNotificationsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> showNotification({
    required int? id,
    required String? title,
    required String? body,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#showNotification, [], {
              #id: id,
              #title: title,
              #body: body,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> showQueuedNotification(int? count) =>
      (super.noSuchMethod(
            Invocation.method(#showQueuedNotification, [count]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateSyncProgress(int? done, int? total) =>
      (super.noSuchMethod(
            Invocation.method(#updateSyncProgress, [done, total]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> showFailedNotification(int? count) =>
      (super.noSuchMethod(
            Invocation.method(#showFailedNotification, [count]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> dismissSyncNotification() =>
      (super.noSuchMethod(
            Invocation.method(#dismissSyncNotification, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
